sudo: false
language: node_js
node_js:
  - "node"
env:
  global:
    - COVERALLS_PARALLEL=true
scripts:
  - COVERALLS_FLAG_NAME=test-1 make test-coverage-1
  - COVERALLS_FLAG_NAME=test-2 make test-coverage-2

notifications:
  webhooks: https://coveralls.io/webhook