version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: node/default

    steps:
      - checkout

      - node/with-cache:
          steps:
            - run: npm install
            - run: make test-coverage

      - run: wget -c -q https://github.com/coverallsapp/coverage-reporter/releases/download/0.1.3/coveralls-linux.tar.gz -O - | tar -xz && ./coveralls

workflows:
  test_then_upload:
    jobs:
      - build

