on: ["push","pull_request"]

name: build

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_number:
          - 1
          - 2
    steps:
      - uses: actions/checkout@master
      - name: environment
        run: |
          echo "export COVERALLS_ENDPOINT=https://coveralls-nick.ngrok.io" > ~/.bashrc
          echo "export COVERALLS_REPO_TOKEN=Aff25AMpEmGTWwx9s0mjuakIe5AINw6H9" > ~/.bashrc
      - uses: actions/setup-node@master
        with:
          version: 10.x
      - run: npm install
      - run: npm run test-coveralls-${{ matrix.test_number }}
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.0
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.github_token }}
          parallel: true
          flag-name: run-${{ matrix.test_number }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true